### ISSUE TITLE
Broken Schema types

### ISSUE THREAD

**Issue by joeyfigaro** [gsimone/use-tweaks#52]
Using typescript `4.4.2`, use-tweaks `0.3.1`, and tweakpane `3.1.0`:
![image](https://user-images.githubusercontent.com/1386477/203460722-a45528dd-fa62-423a-8aa0-f12c97729105.png)

![image](https://user-images.githubusercontent.com/1386477/203460839-e11577e0-ffe2-4fbc-a3c7-78613ecbd77c.png)

![image](https://user-images.githubusercontent.com/1386477/203460916-2f5e1cd7-f252-4cdd-aa11-23fd0c0bda45.png)

Return type for `useTweaks` is `{}`, regardless of whether I pass in a type for the `Schema` generic or not. Am I missing something?

**Comment by joeyfigaro** [comment]
I tried upgrading use-tweaks to `v0.3.2-alpha.0` and the issue seems to have been addressed

![image](https://user-images.githubusercontent.com/1386477/203568426-f24af604-acb5-477f-9509-0089360e927d.png)

**Comment by alecmce** [comment]
I just upgraded to `"use-tweaks": "0.3.2-alpha.0"` and still see the problem you describe. 🤷

**Comment by boenfu** [comment]
> I just upgraded to `"use-tweaks": "0.3.2-alpha.0"` and still see the problem you describe. 🤷

you need install
https://www.npmjs.com/package/@tweakpane/core
![image](https://github.com/tweakpane/use-tweaks/assets/33797740/8097f5cc-521b-4370-9a81-6b43e948be66)

![image](https://github.com/tweakpane/use-tweaks/assets/33797740/b53d09c5-4bdb-4236-9e74-1b23537dce07)
`InputParams` from @tweakpane/core，not existed will break at red box
